### ISSUE TITLE
Create forwarding link for old wiki content

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares.org#102]
Please create a forwarder for:
http://wiki.bitshares.org/index.php/Market_Peg

It is referenced within this article:
https://blog.ethereum.org/2014/08/21/introduction-futarchy/

**Comment by dls-cipher** [comment]
> Please create a forwarder for:
> http://wiki.bitshares.org/index.php/Market_Peg
> 
> It is referenced within this article:
> https://blog.ethereum.org/2014/08/21/introduction-futarchy/

**Comment by dls-cipher** [comment]
@ryanRfox - Done. 
http://wiki.bitshares.org/index.php/Market_Peg -> https://bitshares.org/technology/price-stable-cryptocurrencies/

Permanent 302.

Chee®s
