### ISSUE TITLE
Question on DPoS whitepaper: produce a block at a fixed schedule of one block how many seconds

### ISSUE THREAD

**Issue by betachen** [bitshares/bitshares.org#109]
https://bitshares.org/technology/delegated-proof-of-stake-consensus/

> The slate of active witnesses is updated once every maintenance interval (1 day) when the votes are tallied. They are then shuffled, and each witness given a turn to produce a block at a fixed schedule of one block every **2 seconds**. After all the witnesses have had a turn, they are shuffled again. If a witness does not produce a block in their time slot, then that time slot is skipped, and the next witness produces the next block.

It says 2 seconds

AND 

https://cryptofresh.com/witnesses
> The slate of active witnesses is updated once every maintenance interval (1 day) when the votes are tallied. The witnesses are then shuffled, and each witness is given a turn to produce a block at a fixed schedule of one block every **3 seconds**. After all witnesses have had a turn, they are shuffled again. If a witness does not produce a block in their time slot, then that time slot is skipped, and the next witness produces the next block.

It says 3 seconds

So which one is correct?

**Comment by abitmore** [comment]
On BitShares blockchain, the block interval is 3 seconds. We might need to update the info on the website.

**Comment by betachen** [comment]
thx
