### ISSUE TITLE
block explorer link

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares.org#15]
The block explorer link at the footer is going to https://bitshares-explorer.io/ while it should go to http://bitshares-explorer.io/ until a cert is added there.

Strange thing is that i was about to submit a pull request for it but i see it is correct in the htmls: 
- https://github.com/bitshares/bitshares.org/blob/decentralized-soft-launch/contact.html#L181
- https://github.com/bitshares/bitshares.org/blob/decentralized-soft-launch/index.php#L499

So i am unsure if the live one is another branch or how it works, need to inform the community where we can send pull request.

I see also that the footer is repeated on each content page, contact, index, etc while it is the same thing all the time. You guys are probably already aware of this but you can convert all pages to php and use `include("footer.php");` so when you make changes there they will be done for all sections.

By the way the site looks great IMHO so keep the good work up. Thanks.

**Comment by dls-cipher** [comment]
@oxarbitrage 

- Current github Code is outdated, full version is in php and php external files are being called by require(...); 

- I've had pretty nasty accident today in a family, so there is possibility that upload of current work to github will be postponed for tomorrow. I'll do my best to upload tonight.

All pages on live bitshares.org are in php (try by adding extension to the end of the url).

Chee®s

**Comment by dls-cipher** [comment]
Btw, sorry for ignorance on the link. https to http will be done in few mins.

**Comment by oxarbitrage** [comment]
By the way, the explorer link can be changed back to https if we want as i added cert there some time ago: https://bitshares-explorer.io/
