### ISSUE TITLE
replace explore button with uniform header

### ISSUE THREAD

**Issue by akernest** [bitshares/bitshares.org#19]
-header should look like this page (https://bitshares.org/how-it-works) on all pages
-add “bitshares” next to bitshares logo in header
-header should blend in with home page, like on ripple.com
-remove home link from header
-make “Get Started” button green (on all pages except for home page)
-replace gateways in header with Deposit

**Comment by cassiopaia** [comment]
i'm not a friend of this task ..

**Comment by akernest** [comment]
this is what bytemaster wants. ultimately, he said that it's his decision.
please follow through

Adam Kaleb Ernest | CEO


Follow My Vote, Inc.

2020 Kraft Drive, Suite 3040

Blacksburg, VA 24060


Direct: 540-491-4921

Mobile: 757-876-8340

FollowMyVote.com
<http://t.signaledue.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZvTW5w02yj8pTxVRW5vMrTT56dzQDf7tTlM802?t=http%3A%2F%2Ffollowmyvote.com%2F&si=5363291317075968&pi=9738205b-fcb2-4c13-fb0c-77821826808d>


Notice: This message is intended only for the use of the Addressee and may
contain information that is PRIVILEGED and CONFIDENTIAL. If you are not the
intended recipient, you are hereby notified that any dissemination of this
communication is strictly prohibited.

**Comment by akernest** [comment]
this is what bytemaster wants. ultimately, he said that it's his decision. please follow through

**Comment by cassiopaia** [comment]
mh :( ok then i'm not longer responsible for site design! IMO it really makes no sense if Bytemaster destroy all my design after publishd ... thats my 2 cents

**Comment by cassiopaia** [comment]
why i've created screen designs before?

**Comment by cassiopaia** [comment]
ok so then i've to use 2 different logos cause of the dark background ... if nav should be like ripple also then it only works with 2 logo colors ... due the background ...

**Comment by cassiopaia** [comment]
problem on these things is .. thats why i've created a screen design before ... that if we'll change it now .. .then design and layout will get broke ... IMO .. but you take a look yourself later on ..updating now ..

**Comment by vikramrajkumar** [comment]
This repo has been superseded by: https://github.com/bitshares/bitshares.github.io
