### ISSUE TITLE
Add a link to hackthedex.io

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares.org#2]
As a community member I want a link to https://hackthedex.io (the bounty program) in the new bitshares.org website, so that people who find a security issue will know where and how to report it.

**Comment by dls-cipher** [comment]
For initial launch it can be done as part of the contact page, but for the future there are plans for support system. That system would be able to hold entire department for hackthedex.io and sort inquiries/issues in more sophisticated way. 

@abitmore - If you agree with on Contact page it would be added as disclaimer next to/around contact form.

**Comment by abitmore** [comment]
Thanks. I didn't realize that bitshares.org can directly host all features of hackthedex.io. Please contact @ryanRfox for further discussions and actions.

**Comment by dls-cipher** [comment]
Added to footer, as per commit referenced few mins ago. 

Closed.
