### ISSUE TITLE
make bit asset square icons into coin icons and make them clickable

### ISSUE THREAD

**Issue by akernest** [bitshares/bitshares.org#20]
make sure they link to a page that shows what the BTS vs. bitAsset market page looks like inside the BitShares wallet GUI

**Comment by cassiopaia** [comment]
? how we wanna achieve this!?

**Comment by akernest** [comment]
dan said that the GUI market pages are on github and you should be able to find the code that we can put onsite that would make the market pages display on the website.

**Comment by cassiopaia** [comment]
ok ...

**Comment by cassiopaia** [comment]
ok it would be great if i can get pointed to the specifc pages i should transform and add to site!
I'm feeling a bit helpless with task ...

**Comment by cassiopaia** [comment]
I'm more a designer then a developer so it would be great if someone could assist me with this! Sure i can copy paste html etc over but how to get them worked then to show correct values etc?

**Comment by vikramrajkumar** [comment]
This repo has been superseded by: https://github.com/bitshares/bitshares.github.io
