### ISSUE TITLE
Add project listings to the website

### ISSUE THREAD

**Issue by cnjsstong** [bitshares/bitshares.org#20]
The bitshares.org website acts as a gateway to the BitShares project, especially for new community members and visitors. I kind of feel that it would be great if we could add listings of the projects directly related to the BitShares blockchain. In my mind, I'm thinking about those projects funded by the community through worker proposals, possibly like:

- Core Team: bitshares-core
- UI Team: bitshares-ui, beet ....
- Trusty Team: bitshares-community-ui ...
- BTS++ Team: bitshares-mobile-app
- DEXBot Team: DEXBot
- ROSSUL & Graphene Labs UI/UX Redesign: (looks like no repos for now) 

The purpose of listing is to provide a simple lineup of open-source softwares related to BitShares and let everyone know that we have a complete and powerful ecosystem. At the very beginning we could just list the project name, a short description, a GitHub repo link, and contact info (optional) for each project.

How does this sound like?

**Comment by dls-cipher** [comment]
@richcg 

Create new page in root called bitshares-dapps.php using template for Technology pages.

(GIVE an ESTIMATE as COMMENT here first) ->> On the page create just a list of github dapps (links to their repositories similar to current downloads page) and submit PR. 

P.S. Exclude ROSSUL from the list until there is visible repo on BitShares GitHub.


Later on @cnjsstong and @rsswlkr can follow up on the final content of the page and we can add it to respective menus.

**Comment by richcg** [comment]
Sure. I can create the new dapps page with links. Estimated time is around 30 minutes to an hour.

**Comment by dls-cipher** [comment]
@richcg 

Approved. Log hours in TopTracker and as description use appropriate issue/pr. 

Chee®s

**Comment by richcg** [comment]
Done. Thanks!

**Comment by dls-cipher** [comment]
@cnjsstong - Smaller update to this issue ->> Ross is on the content/seo/listings.

https://github.com/bitshares/bitshares.org/issues/43

Chee®s
