### ISSUE TITLE
login faucet login functionality based on faucet cookie with different views

### ISSUE THREAD

**Issue by akernest** [bitshares/bitshares.org#22]
Home page button should say open your account to new visitors vs. deposit funds to users that have already registered an account through faucet

**Comment by cassiopaia** [comment]
sure but therefor faucet should work with ssl etc...

**Comment by akernest** [comment]
i'm not sure what you mean. ssl seems to be working on faucet just fine

**Comment by cassiopaia** [comment]
Need help from valetine with this task

**Comment by akernest** [comment]
valentine, would you be able to assist cass on completing this task request?

Adam Kaleb Ernest | CEO


Follow My Vote, Inc.

2020 Kraft Drive, Suite 3040

Blacksburg, VA 24060


Direct: 540-491-4921

Mobile: 757-876-8340

FollowMyVote.com
<http://t.signaledue.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZvTW5w02yj8pTxVRW5vMrTT56dzQDf7tTlM802?t=http%3A%2F%2Ffollowmyvote.com%2F&si=5363291317075968&pi=0183578b-d0ba-4a00-ebb5-2519e6ac50de>


Notice: This message is intended only for the use of the Addressee and may
contain information that is PRIVILEGED and CONFIDENTIAL. If you are not the
intended recipient, you are hereby notified that any dissemination of this
communication is strictly prohibited.

**Comment by valzav** [comment]
Sure, I will provide cass with js code that checks user's status - whether it's logged in or not.

**Comment by cassiopaia** [comment]
Thank you Valentine!

**Comment by cassiopaia** [comment]
@valzav any updates on this task!?

**Comment by valzav** [comment]
ok, now you can check user's status via a special call on the widget's object.

Instruction:
Place your logic in some js function, e.g. check_current_user:
  <script>
    function check_current_user() {
       BTSW.current_user(function(user){
         console.log("---- check_current_user : ", user);
       })
    }
  </script>

Then add script.onload = check_current_user to the widget's code:
<script>
var BTSW = window.BTSW || {};
(function () {
var script = document.createElement('script');
script.type = 'text/javascript';
script.async = true;
script.src = 'https://faucet.bitshares.org/widgets/1/w.js?ref='+encodeURIComponent(document.referrer);
script.onload = check_current_user;
var entry = document.getElementsByTagName('script')[0];
entry.parentNode.insertBefore(script, entry);
}());
</script>

**Comment by cassiopaia** [comment]
ok great !! How i can create e.g. a link with if else conditions to display custom content for logged in users!?

**Comment by akernest** [comment]
i will try to follow up with valzav on this to get additional feedback

**Comment by vikramrajkumar** [comment]
This repo has been superseded by: https://github.com/bitshares/bitshares.github.io
