### ISSUE TITLE
Adding Specs. Page

### ISSUE THREAD

**Issue by cassiopaia** [bitshares/bitshares.org#31]

**Comment by cassiopaia** [comment]
any updates?

**Comment by cassiopaia** [comment]
any updates ?

**Comment by xeroc** [comment]
Do you have a structure or template in mind? What content would you like to see for "specs"?
can you point us to something similar at ripple, bitcoin?
how technical should it be?

Nice example: https://bitcoin.org/en/developer-documentation (<- would take ALOT of time & money)

**Comment by cassiopaia** [comment]
I would recommend to have 2 step docs ... 1 step standard technical stuff and step 2 - like a accordion function, not visible at start, mroe detailed techncial information... just an idea!

**Comment by vikramrajkumar** [comment]
This repo has been superseded by: https://github.com/bitshares/bitshares.github.io
