### ISSUE TITLE
[FIX] Blocktivity table limit to top 10

### ISSUE THREAD

**Issue by dls-cipher** [bitshares/bitshares.org#32]
@richcg 

Currently home page is loading Blocktivity table with blockchains listed/ranked by activity. 
In the early days, that table had few projects listed and was looking as nice addition to the bitshares.org, and now that list is 23 projects long. 

For the sense of the SEO and overall on UI/UX experience of the user, i'm requesting a fast and responsive solution to enlist only **top 10 projects**.

Confirm with estimate and let's hit this update as highest priority.

Chee®s

**Comment by richcg** [comment]
This should take me around two hours. I can have it done by tomorrow.
