### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cassiopaia** [bitshares/bitshares.org#49]

**Comment by xeroc** [comment]
I would suggest to not add ANY dates ..
A good start would be something like this:
https://github.com/BitShares/BitShares/milestones (just without the dates)

Also we should add other projects of the community:
metaexchange
btsMUSIC
btsPLAY
wallet.bitshares.org
nathan's light wallet

and some stuff that will be handled after 1.0:
 - turing complete scripting
 - btsVOTE
 - maybe relative orders or so ..

**Comment by vikramrajkumar** [comment]
This repo has been superseded by: https://github.com/bitshares/bitshares.github.io
