### ISSUE TITLE
[Content] Marketing and PR Discussion on first paragraph of Home Page

### ISSUE THREAD

**Issue by dls-cipher** [bitshares/bitshares.org#5]
"Created by Dan (“Bytemaster”) Larimer, BitShares was launched in its existing form on 13th October 2015, and was around prior to that as a community project, ‘protoshares’ since 2013."

Recently came to my attention that this statement is not fully truthful, for a fact. Or it will be completely removed or it will be added as well that he "abandoned" the project. 

- One way or other, we have to express that BitShares 2.0 and what is BitShares today is THANKS TO COMMUNITY DEVELOPERS and VETERANS who stayed around/with Consensus and accepted Blockchain Governance as it is. 
- Also we have to stop giving away too much credits when we in return have none. Especially around new **SEO** that Search Engines will pick up from upcoming website. 

According to MIT, Licence exists and Cryptonomex where BitShares is forked from is signed author/contributor, so more than that is just giving away the actual spotlight from our product/technology to some else where the name is currently active (EOSIO) in this case. 

Proper credits and explanation how this blockchain sustained, survived and is evolving needs to be **BOOM** as info **EVERYWHERE**

I would like to hear opinion from:

@abitmore 
@clockworkgr 
@oxarbitrage 
@pmconrad
@sschiessl-bcp 
@ryanRfox 
@xeroc 

**DISCLAIMER:** Please, keep in mind to remain objective, I do not intend to disrespect, insult or provoke anyone, especially not EOSIO or Daniel Larimer (aka "bytemaster") - this issue is discussion about SEO, Branding, Reputation and real VALUE of BitShares Blockchain.

**Comment by clockworkgr** [comment]
I have long mentioned that with absolutely no disrespect to Dan, we need to stop focusing on the past, how the project came to be and all the things BitShares did first when it comes to blockchain, and instead form a new "manifesto" of sorts of what BitShares is NOW, how it grows and expands and what the future holds.

**Comment by xeroc** [comment]
Two edge sword.
On the one hand we would like to acknowledge the contributors and architects of the past, but on the other hand, they have moved over, or rather left us behind.

Those that know me also know me as a cooperations-guy. This makes it difficult for me to understand Dan's recent shout outs in the EOS community that are targeted against BitShares and bitassets.

Being a contributor to BitShares from the start, it feels inappropriate to credit all the work to Dan while in fact, already in the beginning there were more people involved in building the Ecosystem. I would argue that Dan wouldn't be where he is right now if it wasn't for those people in the past that supported him (and have been left in the dust).

With that in mind, I would personally prefer to focus on status quo and let the past be described in the footnotes.

**Comment by pmconrad** [comment]
> BitShares was launched in its existing form on 13th October 2015, and was around prior to that as a community project, ‘protoshares’ since 2013.

This skips over BitSharesX aka BitShares-1 which launched in July 2014. https://bitsharestalk.org/index.php?topic=5750.0
