### ISSUE TITLE
[DNS] MailChimp - Set Up Custom Domain Authentication: DKIM and SPF

### ISSUE THREAD

**Issue by dls-cipher** [bitshares/bitshares.org#6]
"Authenticate bitshares.org with Mailchimp by modifying your domain's DNS records. These changes allow your campaigns to appear to come from bitshares.org, instead of from Mailchimp servers. After you've made the required DNS changes, please wait 24-48 hours for the changes to propagate."

**DKIM** 
Create a CNAME record for "k1._domainkey.bitshares.org"
with this value: "dkim.mcsv.net"

**SPF** 
Create new TXT record for bitshares.org with:
"v=spf1 include:servers.mcsv.net ?all"

Quotes above ("") are not needed on actual entries.

**Comment by xeroc** [comment]
done
