### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares.org#73]
https://bitshares.org/technology/stakeholder-approved-project-funding/ linked from https://cryptofresh.com/workers and https://cryptofresh.com/fees

**Comment by dls-cipher** [comment]
![2019-05-22_1838](https://user-images.githubusercontent.com/39482961/58171711-c9a35380-7cc0-11e9-98c4-daac424cc727.png)

Any other contacts for owner of cryptofresh.com ? 

Chee®s

**Comment by roadscape** [comment]
CF links have been updated 👍

**Comment by abitmore** [comment]
@roadscape thank you, but the pages now showing "We're sorry, but something went wrong.". Will check later.

**Comment by dls-cipher** [comment]
Thanks again @roadscape :) 

@abitmore - thanks for helping on this one.

Will close this issue once CF gets back online.
