### ISSUE TITLE
Include exhange CCEDK

### ISSUE THREAD

**Issue by liondani** [bitshares/bitshares.org#76]
@cas

please edit this page:
https://bitshares.org/deposit-withdraw

and include CCEDK ecxhange  ;) https://www.ccsedk.com/

see forum post: https://bitsharestalk.org/index.php/topic,16708.msg214091.html#msg214091

**Comment by vikramrajkumar** [comment]
This repo has been superseded by: https://github.com/bitshares/bitshares.github.io
