### ISSUE TITLE
Link to chat groups?

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares.org#77]
I can't find any info about chat groups on the https://bitshares.org/ site.

**Comment by dls-cipher** [comment]
BitShares.org is not having any group associated to promote it, and will not promote Telegram groups without proper rules/moderation.

It was cleared on forums, launch and revision of the website, Move Institute will not list (take legal responsibility for) any shilling groups without proper owner/admin/moderation. Hope you find this reasonable.

P.S. Once translations become active (next 2 weeks sprint), each language will have chat support through the website itself. All messages will be forwarded to Wallet telegram group as tickets/support and replied by admins only. Ofc, for each language we can assign different group, even software, as long it has API open for integration. 

Chee®s
