### ISSUE TITLE
Homepage broken

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares.org#79]
1. ![image](https://user-images.githubusercontent.com/33128181/58866594-2f2c1280-86b9-11e9-92d3-0593b1a0362f.png)

2. ![image](https://user-images.githubusercontent.com/33128181/58866608-34895d00-86b9-11e9-9672-066414bf6ff4.png)

3. Unable to oben submenu of docs (reloads page)

4. 
![image](https://user-images.githubusercontent.com/33128181/58866855-b4afc280-86b9-11e9-99be-d2829bc44bd1.png)

**Comment by sschiessl-bcp** [comment]
@dls-cipher @rsswlkr

**Comment by dls-cipher** [comment]
Reload and be patient/possibly clear cache - implementing CDN integration to production atm

- check page source ->> you'll see content/media loaded from `edge.bitshares.org`

Chee®s

**Comment by dls-cipher** [comment]
Confirmed that CDN was failing to load bunch of data, so turned off (continuing development behind closed doors :P), blocktivity-api.php disabled for now, until Estefan resolves issue. 

This is closed.

Chee®s
