### ISSUE TITLE
Create account page error

### ISSUE THREAD

**Issue by matle85** [bitshares/bitshares.org#80]
Please see attached 
![create account failure](https://user-images.githubusercontent.com/8676205/58874930-3401be00-86db-11e9-90d1-e51a90bb87a2.jpg)

**Comment by dls-cipher** [comment]
`faucet.bitshares.eu:80/api/v1/accounts
Failed to load resource: net::ERR_FAILED`

Faucet is probably down, investigating.

**Comment by dls-cipher** [comment]
![2019-06-04_2047](https://user-images.githubusercontent.com/39482961/58884372-7d1d3680-870a-11e9-8528-7c4237f1d39b.png)

Fixed. uri is not parsing https for some reason, had to add :443 manually.

Chee®s
