### ISSUE TITLE
[Content] BTS Holder Approved Funding

### ISSUE THREAD

**Issue by dls-cipher** [bitshares/bitshares.org#88]
Introduction: As `stakeholder` is very sensitive and specific term in corporate/finance industry, ecosystem decided to represent/name holders of core token on BitShares blockchain simply `BTS holders`.

Requirement: @sschiessl-bcp introduced a change by PR #86. Content must be SEO-friendly incorporating new keyphrase as most common/optimized in the content.

Task:
- Replace any remaining term of `stakeholder` with `BTS holder`
- Check/improve readability
- Check/Improve new keyphrase

ETA: 1 hour.

**Comment by rsswlkr** [comment]
> ETA: 1 hour.

Please see https://github.com/bitshares/bitshares.org/pull/92
