### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares.org#93]
Is anyone testing this stuff? :P
![Peek 2019-06-18 16-18](https://user-images.githubusercontent.com/33128181/59692225-c4182b00-91e4-11e9-8713-a75c1542a3e6.gif)

**Comment by sschiessl-bcp** [comment]
If you need a browserstack account to test compatibility let me know

**Comment by dls-cipher** [comment]
Menu is fine, probably my live CSS linting pulled something down the drain along with that menu. I'll see what part of lint is the cause :)

**Comment by dls-cipher** [comment]
Fixed.
