### ISSUE TITLE
404 page styling

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares.org#95]
![image](https://user-images.githubusercontent.com/33128181/60074282-d6cdbb00-9722-11e9-8f9a-4fa7e96a4cbc.png)

**Comment by allfory0u** [comment]
![Screenshot](https://user-images.githubusercontent.com/17462020/60105227-9e9e9a80-976b-11e9-8c7f-d10e2c3a33cc.jpg)

**Comment by dls-cipher** [comment]
All js/css had a lot of linting in previous versions and somehow 404 page was re-uploaded with old css/js on it. 

Fixed in #98 - will be deployed later today.

Chee®s
